### ISSUE TITLE
maxAvtive and errors

### ISSUE THREAD

**Issue by DrDrulia** [Mmtrx/FS25_BetterContracts#3]
Hello. So far, changing   maxActive="10" is not working. 
 also, keep getting : C:/Users/Druli/Documents/My Games/FarmingSimulator2025/mods/FS25_BetterContracts/scripts/gui.lua:222: attempt to index nil with 'detailsButton'
 2024-12-17 22:40 Error: Running LUA method 'update'.
C:/Users/Druli/Documents/My Games/FarmingSimulator2025/mods/FS25_BetterContracts/betterContracts.lua:547: attempt to index nil with 'seedUsagePerSqm'
2024-12-17 22:40 Error: Running LUA method 'update'.
C:/Users/Druli/Documents/My Games/FarmingSimulator2025/mods/FS25_BetterContracts/betterContracts.lua:547: attempt to index nil with 'seedUsagePerSqm'
2024-12-17 22:40 Error: Running LUA method 'update'.
C:/Users/Druli/Documents/My Games/FarmingSimulator2025/mods/FS25_BetterContracts/betterContracts.lua:547: attempt to index nil with 'seedUsagePerSqm'
2024-12-17 22:40 dataS/character/animals/wild/crow/crow.i3d (14.70 ms)
[log.txt](https://github.com/user-attachments/files/18172144/log.txt)

and another one about seed usage

**Comment by Mmtrx** [comment]
Thanks for testing!
I corrected the seedUsage bug (and also some warnings about missing selling stations). But I cannot reproduce the 1st error (detailsButton).
When editing F25_BetterContracts.xml in your savegamex folder, can you do:
```
<BetterContracts debug="true" ferment="false" forcePlow="false" maxActive="10" ...
```
and maybe try to just disable the other mods, once I upload the patch release (1.0.1.1) for this?

**Comment by DrDrulia** [comment]
usually haven’t when you click it with a mouse

**Comment by FirenzeIT** [comment]
Hi @Mmtrx not yet published BC v1.0.1.1 right?? What is the difference between BC and ContractBoost by GMNGjoy??

**Comment by Mmtrx** [comment]
Should be ok with latest release 1.0.1.1 - but single player only! MP version is coming soon.

**Comment by FirenzeIT** [comment]
Hi, ok but it's possible fix the D button errors?.? It's alway present this error/bug
